## Canary CI/CD
name: Canary Full Flow
run-name: Canary Full Flow

on:
  pull_request:
    branches:
      - "*"
  #push:
    #branches:
      #- master

jobs:
  #test:
    #uses: kaltura/playkit-js-common/.github/workflows/cypress.yml@master
    #secrets: inherit

  canary-full-flow:
    if: ${{ github.actor != 'PlaykitJs-Bot' }}
    uses: kaltura/playkit-js-common/.github/workflows/canary_full_flow_plugin.yaml@0acc2c19c8fa88c798023e9b2ec76b806cacec03
    secrets: inherit
    with:
      schema-type: "playerV3OvpVersions"
      tests-yarn-run-to-execute: 'build'